In [1]:
import warnings #Berfungsi untuk blablabla
import cv2
import random
import numpy as np
import time
import os
from imutils import paths
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

warnings.filterwarnings("ignore")
SEED = 42

In [2]:
time_wait = time.time()
data = []
labels = []

imgPath = sorted(list(paths.list_images('Data')))
random.seed(SEED)
random.shuffle(imgPath)

for imgPath in imgPath:
    img = cv2.imread(imgPath)
    img = cv2.resize(img, (32, 32)).flatten()
    data.append(img)
    
    label = imgPath.split(os.path.sep)[-2]
    labels.append(label)
    
data = np.array(data, dtype="float")/255.0
labels = np.array(labels)

print('Time taken: {:.1f} seconds'.format(time.time() - time_wait))
print('done')

Time taken: 1.3 seconds
done


In [3]:
from sklearn.model_selection import train_test_split

(x_train, x_test, y_train, y_test) = train_test_split(data, labels, test_size=0.2, random_state=SEED)

In [4]:
x_train

array([[0.82745098, 0.85490196, 0.85882353, ..., 0.74117647, 0.77647059,
        0.81176471],
       [0.07843137, 0.05882353, 0.0627451 , ..., 0.03921569, 0.30196078,
        0.54117647],
       [0.00392157, 0.84313725, 0.55294118, ..., 0.10196078, 0.19215686,
        0.10980392],
       ...,
       [0.02745098, 0.22745098, 0.20784314, ..., 0.68627451, 0.81176471,
        0.90980392],
       [0.54901961, 0.92941176, 0.78431373, ..., 0.25098039, 0.5372549 ,
        0.43529412],
       [0.53333333, 0.74117647, 0.72941176, ..., 0.5254902 , 0.78823529,
        0.75294118]])

In [5]:
y_train

array(['Anjing', 'Kucing', 'Burung', 'Burung', 'Kucing', 'Kucing',
       'Kucing', 'Anjing', 'Anjing', 'Anjing', 'Burung', 'Burung'],
      dtype='<U6')

In [6]:
type(y_train)

numpy.ndarray

In [7]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

#Apabila hanya ingin klasifikasi 2 variabel maka dapat menggunakan kode di bawah ini
#from keras.utils import to_categorical
#y_test = to_categorical(y_test)
#y_train = to_categorical(y_train)

In [8]:
y_train

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [9]:
y_test

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [10]:
print(img.shape)

(3072,)


In [11]:
len(lb.classes_)

3

In [16]:
from keras.models import Sequential
from keras.layers.core import Dense

print('[INFO] Makig Model')
model = Sequential() #input 32x32x3=3072 px
model.add(Dense(1024, input_shape=(3072,), activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(len(lb.classes_), activation='softmax'))

[INFO] Makig Model


In [17]:
from keras.optimizers import SGD

INIT_LR = 0.01
EPOCHS = 60
 
# Untuk melakukan compile model dapat menggunakan SGD sebagai optimasi dan menggunakan categorical_crossentropy untuk Loss
print("[INFO] Training Network")
opt = SGD(lr=INIT_LR)   # Stochastic Gradient Descent (SGD) optimizer
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])

[INFO] Training Network


In [22]:
time1 = time.time()
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=50, batch_size=32)
print('Time taken: {:.1f} seconds'.format(time.time() - time1))

Train on 12 samples, validate on 3 samples
Epoch 1/50
12/12 [==============================] - 0s 10ms/step - loss: 0.0263 - acc: 1.0000 - val_loss: 1.8267 - val_acc: 0.3333
Epoch 2/50
12/12 [==============================] - 0s 10ms/step - loss: 0.0260 - acc: 1.0000 - val_loss: 1.8285 - val_acc: 0.3333
Epoch 3/50
12/12 [==============================] - 0s 11ms/step - loss: 0.0257 - acc: 1.0000 - val_loss: 1.8314 - val_acc: 0.3333
Epoch 4/50
12/12 [==============================] - 0s 14ms/step - loss: 0.0255 - acc: 1.0000 - val_loss: 1.8330 - val_acc: 0.3333
Epoch 5/50
12/12 [==============================] - 0s 14ms/step - loss: 0.0252 - acc: 1.0000 - val_loss: 1.8367 - val_acc: 0.3333
Epoch 6/50
12/12 [==============================] - 0s 12ms/step - loss: 0.0249 - acc: 1.0000 - val_loss: 1.8383 - val_acc: 0.3333
Epoch 7/50
12/12 [==============================] - 0s 17ms/step - loss: 0.0247 - acc: 1.0000 - val_loss: 1.8408 - val_acc: 0.3333
Epoch 8/50
12/12 [======================